/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbprogram;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Montek
 */
public class GuestZipSearchView extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form GuestZipSearchView
     */
    public GuestZipSearchView(Connection conn) {
        con = conn;
        initComponents();
    }
    public GuestZipSearchView() {
        initComponents();
    }
    
    public void updateView() throws SQLException{
        petTypeMenu.add(" ");
        petTypeMenu.add("Cat");
        petTypeMenu.add("Dog");
        petGenderMenu.add("M");
        petGenderMenu.add("F");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        zipField = new javax.swing.JTextField();
        zipSrchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        petTypeMenu = new java.awt.Choice();
        petBreedMenu = new java.awt.Choice();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        petGenderMenu = new java.awt.Choice();
        petSrchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search");

        jLabel2.setText("Enter Zip");

        zipField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipFieldActionPerformed(evt);
            }
        });

        zipSrchBtn.setText("Zip Search");
        zipSrchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipSrchBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Pet Search");

        petTypeMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petTypeMenuItemStateChanged(evt);
            }
        });

        jLabel4.setText("Pet Type");

        jLabel5.setText("Breed");

        jLabel6.setText("Gender");

        petSrchBtn.setText("Search");
        petSrchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petSrchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(petGenderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(petTypeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(zipSrchBtn))
                                            .addComponent(petBreedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(petSrchBtn)))))
                            .addComponent(jLabel3))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipSrchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(petTypeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petBreedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(petGenderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petSrchBtn)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zipFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipFieldActionPerformed

    private void petTypeMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petTypeMenuItemStateChanged
        if("Cat".equals(petTypeMenu.getSelectedItem())){
            try {
                petBreedMenu.removeAll();
                Statement st = con.createStatement();
                String sql = ("SELECT * FROM catbreed");
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    petBreedMenu.add(rs.getString(1));
                }     
            } catch (SQLException ex) {
                Logger.getLogger(GuestZipSearchView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                 petBreedMenu.removeAll();
                Statement st = con.createStatement();
                String sql = ("SELECT * FROM dogbreed");
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    petBreedMenu.add(rs.getString(1));
                }  
                    
            } catch (SQLException ex) {
                Logger.getLogger(GuestZipSearchView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
            
    }//GEN-LAST:event_petTypeMenuItemStateChanged

    private void zipSrchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipSrchBtnActionPerformed
           ZipSearchView view = new ZipSearchView(con, zipField.getText());
        try {
            view.updateView();
        } catch (SQLException ex) {
            Logger.getLogger(GuestZipSearchView.class.getName()).log(Level.SEVERE, null, ex);
        }
           view.setVisible(true);
           
    }//GEN-LAST:event_zipSrchBtnActionPerformed

    private void petSrchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petSrchBtnActionPerformed
        String petType = petTypeMenu.getSelectedItem();
        String breed = petBreedMenu.getSelectedItem();
        String gender = petGenderMenu.getSelectedItem();
        PetSearch view = new PetSearch(con, petType, breed, gender);
        try {
            view.updateView();
        } catch (SQLException ex) {
            Logger.getLogger(GuestZipSearchView.class.getName()).log(Level.SEVERE, null, ex);
        }
        view.setVisible(true);
        
    }//GEN-LAST:event_petSrchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestZipSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestZipSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestZipSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestZipSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestZipSearchView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.Choice petBreedMenu;
    private java.awt.Choice petGenderMenu;
    private javax.swing.JButton petSrchBtn;
    private java.awt.Choice petTypeMenu;
    private javax.swing.JTextField zipField;
    private javax.swing.JButton zipSrchBtn;
    // End of variables declaration//GEN-END:variables
}
