/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbprogram;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Montek
 */
public class PetFosterForm extends javax.swing.JFrame {
    Connection con;
    String shelter;
    /**
     * Creates new form PetFosterForm
     */
    public PetFosterForm(Connection conn, String shelter) {
        con = conn;
        this.shelter = shelter;
        initComponents();
    }
    
    public PetFosterForm() {
        initComponents();
    }
    
    public void updateView() throws SQLException{
        Statement st = con.createStatement();
        String sql = ("SELECT         P.`PetID`\n" +
                      "FROM           Pet AS P \n" +
                      "WHERE          P.ShelterName = 'Best Pets'\n" +
                      "ORDER BY       PetID"
                      );
        ResultSet rs = st.executeQuery(sql);
        
        while(rs.next()){
            petIDMenu.add(rs.getString(1));
              
        } 
        
        sql = ("SELECT         F.Name, F.Phone\n" +
               "FROM           Fosterer AS F     \n" +
               "ORDER BY       Name"
              );
        rs = st.executeQuery(sql);
        while(rs.next()){
            nameMenu.add(rs.getString(1));
            phoneMenu.add(rs.getString(2));
        } 
        
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        petIDMenu = new java.awt.Choice();
        nameMenu = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phoneMenu = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameMenuItemStateChanged(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("PetId");

        jLabel2.setText("Name-Phone");

        jLabel3.setText("Assign pet from this shelter to a Foster Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(petIDMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petIDMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String petID = petIDMenu.getSelectedItem();
        String name = nameMenu.getSelectedItem();
        String phone = phoneMenu.getSelectedItem();
        Statement st;
        try {
            st = con.createStatement();
            String sql = ("SELECT YEAR(CURRENT_DATE), COUNT( DISTINCT PDA.PetID ) , COUNT( DISTINCT PDN.PetID) , COUNT( DISTINCT PDS.PetID) , COUNT( DISTINCT PDF.PetID ), COUNT( DISTINCT PCA.PetID ) , COUNT( DISTINCT PCN.PetID) , COUNT( DISTINCT PCS.PetID) , COUNT( DISTINCT PCF.PetID )\n" +
"FROM Shelter AS S\n" +
"LEFT OUTER JOIN Pet AS PDA ON ( S.ShelterName = PDA.ShelterName AND PDA.Type = 'Dog'\n" +
"AND YEAR( PDA.ADate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PDN ON ( S.ShelterName = PDN.ShelterName AND PDN.Type = 'Dog'\n" +
"AND YEAR( PDN.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PDS ON ( S.ShelterName = PDS.ShelterName AND PDS.Type = 'Dog'\n" +
"AND YEAR( PDS.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PDF ON ( S.ShelterName = PDF.ShelterName AND PDF.FName IS NOT NULL AND PDF.Type = 'Dog'\n" +
"AND YEAR( PDF.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PCA ON ( S.ShelterName = PCA.ShelterName AND PCA.Type = 'Cat'\n" +
"AND YEAR( PCA.ADate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PCN ON ( S.ShelterName = PCN.ShelterName AND PCN.Type = 'Cat'\n" +
"AND YEAR( PCN.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PCS ON ( S.ShelterName = PCS.ShelterName AND PCS.Type = 'Cat'\n" +
"AND YEAR( PCS.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"LEFT OUTER JOIN Pet AS PCF ON ( S.ShelterName = PCF.ShelterName AND PCF.FName IS NOT NULL AND PCF.Type = 'Cat'\n" +
"AND YEAR( PCF.SDate ) = YEAR( CURRENT_DATE( ) ) )\n" +
"GROUP BY YEAR(CURRENT_DATE)"
                         );
        ResultSet rs = st.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(PetFosterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameMenuItemStateChanged
        int name = nameMenu.getSelectedIndex();
        phoneMenu.select(name);
    }//GEN-LAST:event_nameMenuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetFosterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetFosterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetFosterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetFosterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetFosterForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Choice nameMenu;
    private java.awt.Choice petIDMenu;
    private java.awt.Choice phoneMenu;
    // End of variables declaration//GEN-END:variables
}
